import enum

class GUIKey(enum.Enum):
    SERVICE_DISPLAY = enum.auto()
    RAILOS_LOC_BROWSER = enum.auto()
    RAILOS_LOC = enum.auto()
    TIMETABLE_DISPLAY = enum.auto()
    SRV_START_TIME = enum.auto()
    UNIT_SELECT = enum.auto()
    CONSIST_TEMPLATES = enum.auto()
    SERVICE_REF = enum.auto()
    SERVICE_DESC = enum.auto()
    RADIO_SRV_SELECT = enum.auto()
    RADIO_SRV_FINISH_SELECT = enum.auto()
    CHOOSE_BY_LOCATION = enum.auto()
    TRACK_IDS = enum.auto()
    LOCATION_SELECT = enum.auto()
    TRACK_ID_REAR = enum.auto()
    TRACK_ID_FRONT = enum.auto()
    EXIT_LOCATION_IDS = enum.auto()
    FINISH_SRV_REF = enum.auto()
    MANUAL_TERMINATION = enum.auto()
    MANUAL_TERMINATION_TIME = enum.auto()
    PARENT_SRV_REF = enum.auto()
    SHUTTLE_REF = enum.auto()
    SHUTTLE_RETURN_REF = enum.auto()
    FEEDER_SRV_REF = enum.auto()
    REPEATS_N = enum.auto()
    REPEATS_MINS = enum.auto()
    REPEATS_INC = enum.auto()
    INSERT_EDIT = enum.auto()
    DELETE = enum.auto()
    CLEAR = enum.auto()
    CLONE = enum.auto()
    ROUTE_BROWSER = enum.auto()
    ROUTE_CHOICE = enum.auto()