name: Railway Operation Simulator Timetable Editor
on:
  [push]
jobs:
  build:
    name: Build ROSTTB Editor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
      - name: Install GNU Make
        run: sudo apt install make -y
      - name: Build Editor
        run: qmake && make
      
